In [4]:
import polars as pl

In [5]:
df_train = pl.read_csv("./FungiTastic/metadata/FungiTastic-Mini/FungiTastic-Mini-Train.csv")
print(len(df_train))

46842

In [7]:
df_train.describe()

shape: (9, 33)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ eventDate ┆ year      ┆ month    ┆ … ┆ elevation ┆ landcover ┆ biogeogra ┆ captions  │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ phicalReg ┆ ---       │
│ str       ┆ str       ┆ f64       ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ion       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ ---       ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ str       ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 46842     ┆ 46842.0   ┆ 46842.0  ┆ … ┆ 46799.0   ┆ 46799.0   ┆ 46760     ┆ 46769     │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0      ┆ … ┆ 43.0      ┆ 43.0      ┆ 82        ┆ 73        │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 2017.9774 ┆ 8.870629 ┆ … ┆ 67.640377 ┆ 11.569093 ┆ null      ┆ null      │
│           ┆           ┆ 35        ┆          ┆   ┆           ┆           ┆           ┆           │
│ std       ┆ null      ┆ 3.484181  ┆ 1.823644 ┆ … ┆ 139.21810 ┆ 5.490019  ┆ null      ┆ null      │
│           ┆           ┆           ┆          ┆   ┆ 9         ┆           ┆           ┆           │
│ min       ┆ 1963-08-1 ┆ 1963.0    ┆ 1.0      ┆ … ┆ 0.0       ┆ 1.0       ┆ alpine    ┆ The       │
│           ┆ 5         ┆           ┆          ┆   ┆           ┆           ┆           ┆ basket    │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ contains  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ a diverse │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ …         │
│ 25%       ┆ null      ┆ 2017.0    ┆ 8.0      ┆ … ┆ 0.0       ┆ 8.0       ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ 2019.0    ┆ 9.0      ┆ … ┆ 13.0      ┆ 12.0      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ 2020.0    ┆ 10.0     ┆ … ┆ 73.0      ┆ 17.0      ┆ null      ┆ null      │
│ max       ┆ 2021-12-3 ┆ 2021.0    ┆ 12.0     ┆ … ┆ 2313.0    ┆ 17.0      ┆ pannonian ┆ The tree  │
│           ┆ 1         ┆           ┆          ┆   ┆           ┆           ┆           ┆ trunk is  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ adorned   │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ with…     │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
df_val = pl.read_csv("./FungiTastic/metadata/FungiTastic-Mini/FungiTastic-Mini-Val.csv")
print(len(df_val))

9412

In [9]:
df_val.describe()

shape: (9, 30)
┌────────────┬────────────┬────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ eventDate  ┆ year   ┆ month    ┆ … ┆ category_i ┆ metaSubst ┆ poisonous ┆ captions  │
│ ---        ┆ ---        ┆ ---    ┆ ---      ┆   ┆ d          ┆ rate      ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ f64    ┆ f64      ┆   ┆ ---        ┆ ---       ┆ f64       ┆ str       │
│            ┆            ┆        ┆          ┆   ┆ f64        ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 9412       ┆ 9412.0 ┆ 9412.0   ┆ … ┆ 9412.0     ┆ 9412      ┆ 9412.0    ┆ 9391      │
│ null_count ┆ 0          ┆ 0.0    ┆ 0.0      ┆ … ┆ 0.0        ┆ 0         ┆ 0.0       ┆ 21        │
│ mean       ┆ null       ┆ 2022.0 ┆ 9.249788 ┆ … ┆ 88.196345  ┆ null      ┆ 0.185083  ┆ null      │
│ std        ┆ null       ┆ 0.0    ┆ 1.569613 ┆ … ┆ 62.873816  ┆ null      ┆ 0.388385  ┆ null      │
│ min        ┆ 2022-01-01 ┆ 2022.0 ┆ 1.0      ┆ … ┆ 1.0        ┆ animals   ┆ 0.0       ┆ The       │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ basket    │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ contains  │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ a diverse │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ …         │
│ 25%        ┆ null       ┆ 2022.0 ┆ 9.0      ┆ … ┆ 35.0       ┆ null      ┆ 0.0       ┆ null      │
│ 50%        ┆ null       ┆ 2022.0 ┆ 10.0     ┆ … ┆ 78.0       ┆ null      ┆ 0.0       ┆ null      │
│ 75%        ┆ null       ┆ 2022.0 ┆ 10.0     ┆ … ┆ 144.0      ┆ null      ┆ 0.0       ┆ null      │
│ max        ┆ 2022-12-31 ┆ 2022.0 ┆ 12.0     ┆ … ┆ 214.0      ┆ wood      ┆ 1.0       ┆ The jar   │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ contains  │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ a variety │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ of …      │
└────────────┴────────────┴────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [18]:
print(f"Poisonous mushrooms : {len(df_train.filter(pl.col("poisonous") == True))}")
print(f"Safe mushrooms      : {len(df_train.filter(pl.col("poisonous") == False))}")

Poisonous mushrooms : 5843
Safe mushrooms      : 40999

In [17]:
print(f"Poisonous mushrooms : {len(df_val.filter(pl.col("poisonous") == True))}")
print(f"Safe mushrooms      : {len(df_val.filter(pl.col("poisonous") == False))}")

Poisonous mushrooms : 1742
Safe mushrooms      : 7670